# Generated by Django 3.1.1 on 2020-10-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speeds', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
