# Generated by Django 3.1.1 on 2020-11-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20201107_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.cars'),
        ),
    ]
