# Generated by Django 3.1.1 on 2020-10-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_speeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speeds',
            name='speeds',
            field=models.CharField(max_length=100),
        ),
    ]
