# Generated by Django 3.1.1 on 2020-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20201020_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speeds',
            name='speeds',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
