# Generated by Django 3.1.1 on 2020-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20201108_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Mileage'),
        ),
    ]
