# Generated by Django 3.1.1 on 2020-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20201108_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
